### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by brandonjjon** [kangguru/botvac#1]
Hi there,

Getting this issue when trying to login.

```
botvac robots
Email: brandonjjonx@gmail.com
Pasword: 
/Users/bjones/.rvm/gems/ruby-2.2.0/gems/botvac-0.1.2/lib/botvac/cli.rb:23:in `robots': undefined method `each' for nil:NilClass (NoMethodError)
    from /Users/bjones/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/bjones/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/bjones/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/bjones/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/bjones/.rvm/gems/ruby-2.2.0/gems/botvac-0.1.2/bin/botvac:5:in `<top (required)>'
    from /Users/bjones/.rvm/gems/ruby-2.2.0/bin/botvac:23:in `load'
    from /Users/bjones/.rvm/gems/ruby-2.2.0/bin/botvac:23:in `<main>'
    from /Users/bjones/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/bjones/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by brandonjjon** [comment]
Nevermind, wrong password!
